remote_theme: mmistakes/minimal-mistakes


# Enable table of contents
toc: true
toc_depth: 3

# Layout for a single-page documentation site
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-relative-links