remote_theme: just-the-docs/just-the-docs

# Enable or disable the site search
search_enabled: true

# Optional: Configure TOC settings
just_the_docs:
  show_toc: true
  toc_levels: 1..3  # Adjust levels as needed