remote_theme: just-the-docs/just-the-docs

# Site settings
title: Arduino Logger Guide
description: ANU PHYS2020 course project Arduino quick start tutorial

# Enable sidebar TOC
just_the_docs:
  show_toc: true
  toc_depth: 3

  # Customize color scheme
  palette:
    primary: "#3498db"      # Change to your desired primary color
    secondary: "#2ecc71"    # Change to your desired secondary color

# Single page setup
single_page: true
