# Minimal Mistakes Configuration
remote_theme: minimal-mistakes

# Enable the table of contents
plugins:
  - jekyll-toc

toc:
  # Position can be 'left' or 'right'
  position: left
  # Maximum heading depth to include in TOC
  depth: 4