# Theme configuration
remote_theme: vaibhavvikas/jekyll-theme-minimalistic
title: PHYS2020 Arduino Quick Start
description: "Thermodynamics Course Arduino Guide"
logo: false
favicon: false
navbar: true
navigation: true
highlighter: rouge

# Theme appearance
color-scheme: light
show_downloads: false

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme

# Other settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  toc_levels: 1..3