title: PHYS2020 Arduino Quick Start
description: ANU PHYS2020 course project Arduino quick start tutorial
theme: minima

markdown: kramdown
kramdown:
  input: GFM

# Use the custom layout for the homepage
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"