remote_theme: just-the-docs/just-the-docs

# Enable or disable the site search
search_enabled: true

# Configure TOC settings
kramdown:
  toc_levels: 1..3

# Theme settings
aux_links:
  "View on GitHub":
    - "https://github.com/TonyXTYan/PHYS2020-Arduino-Quick-Start"

# Enable navigation
nav_enabled: true

# Show table of contents for all pages
toc:
  enabled: true
  h_min: 1
  h_max: 3