theme: jekyll-theme-minimal
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-toc
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
toc:
  min_level: 1
  max_level: 3
  no_toc_section_class: 'd-none'
