theme: jekyll-theme-minimal
title: PHYS2020 Arduino Quick Start
description: Quick start guide for Arduino-based data logging in PHYS2020

markdown: kramdown
kramdown:
  parse_block_html: true
  auto_ids: true
  toc_levels: 1..3

# Show table of contents
toc:
  enabled: true
  h_min: 1
  h_max: 3