remote_theme: kitian616/jekyll-TeXt-theme

title: "My Guide"
description: "Tutorial from README.md"

include:
  - README.md

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: post
      toc: true
