remote_theme: just-the-docs/just-the-docs
title: PHYS2020 Arduino Quick Start
description: Quick start guide for Arduino-based data logging in PHYS2020

color_scheme: light

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/TonyXTYan/PHYS2020-Arduino-Quick-Start"

# Enable navigation and TOC
nav_enabled: true
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2024 Tony Yan"

# Enable TOC on every page
enable_copy_code_button: true
