# filepath: /Users/tonyyan/Documents/_ANU/_PHYS2020/Project Notes/PHYS2020 Arduino Quick Start/_config.yml
theme: just-the-docs

# Optional: Configure TOC settings
just_the_docs:
  show_toc: true
  toc_levels: 1..3  # Adjust levels as needed