  remote_theme: pmarsceill/just-the-docs
  plugins:
    - jekyll-remote-theme

  just_the_docs:
    toc: true
    toc_label: "Table of Contents"
    toc_icon: "list-alt"
    toc_sticky: true
    toc_levels: 1..6