remote_theme: just-the-docs/just-the-docs
title: PHYS2020 Arduino Quick Start
description: Quick start guide for Arduino-based data logging in PHYS2020

color_scheme: light

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/TonyXTYan/PHYS2020-Arduino-Quick-Start"

# Enable navigation
has_nav: true
nav_external_links:
  - title: GitHub Repository
    url: https://github.com/TonyXTYan/PHYS2020-Arduino-Quick-Start
    hide_icon: false

# Enable TOC on every page
has_toc: true

# Configure heading levels for navigation
nav_level: 3

# Show table of contents in left sidebar
toc:
  enabled: true
  h_min: 1
  h_max: 3